version: '3.7'

services:
    minio:
        restart: always
        image: minio/minio:latest
        container_name: s3
        ports:
            - "9000:9000"
            - "9001:9001"
        command: server /data --console-address ':9001' --address ':9000'
        env_file:
            - .env
        environment:
            - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
            - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}

    mc:
        image: minio/mc:latest
        depends_on:
            - minio
        container_name: mc
        env_file:
            - .env
        entrypoint: >
            /bin/sh -c "
            mc alias set minio http://minio:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} &&
            mc mb minio/mlflow;
            exit 0;
            "

    mlflow:
        restart: always
        build: ./mlflow
        container_name: mlflow
        depends_on:
            - mc
        ports:
            - "8000:8000"
        env_file:
            - .env
        environment:
            - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        command: mlflow server --default-artifact-root s3://mlflow/ --host 0.0.0.0 -p 8000

    tensorflow:
        build: ./tensorflow
        container_name: tensorflow
        depends_on:
            - mlflow
        env_file:
            - .env
        environment:
            - MLFLOW_TRACKING_URI=http://mlflow:8000
            - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        command: python /src/train.py

    xgboost:
        build: ./xgboost
        container_name: xgboost
        depends_on:
            - mlflow
        env_file:
            - .env
        environment:
            - MLFLOW_TRACKING_URI=http://mlflow:8000
            - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        command: python /src/train.py

    pytorch:
        build: ./pytorch
        container_name: pytorch
        depends_on:
            - mlflow
        env_file:
            - .env
        environment:
            - MLFLOW_TRACKING_URI=http://mlflow:8000
            - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        command: python /src/train.py

    mlflow-modal:
        build: ./mlflow-modal
        container_name: mlflow-modal
        depends_on:
            - mlflow
            - tensorflow
        env_file:
            - .env
        environment:
            - MLFLOW_TRACKING_URI=http://mlflow:8000
            - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - MODAL_TOKEN_ID=${MODAL_TOKEN_ID}
            - MODAL_TOKEN_SECRET=${MODAL_TOKEN_SECRET}
            - MODAL_WORKSPACE=${MODAL_WORKSPACE}
        command: bin/sh -c "sleep infinity"
