version: '3.7'

services:
    minio:
        restart: always
        image: minio/minio:latest
        container_name: s3
        ports:
            - "9000:9000"
            - "9001:9001"
        command: server /data --console-address ':9001' --address ':9000'
        env_file:
            - .env
        environment:
            - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
            - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}

    mc:
        image: minio/mc:latest
        depends_on:
            - minio
        container_name: mc
        env_file:
            - .env
        entrypoint: >
            /bin/sh -c "
            mc alias set minio http://minio:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} &&
            mc mb minio/mlflow;
            exit 0;
            "

    postgres:
        restart: always
        image: postgres:latest
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            - PGDATABASE=${PGDATABASE}
            - PGUSER=${PGUSER}
            - PGPASSWORD=${PGPASSWORD}
    
    mlflow:
        restart: always
        build: ./mlflow
        container_name: mlflow
        depends_on:
            - mc
            - postgres
        ports:
            - "8000:8000"
        env_file:
            - .env
        environment:
            - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - PGDATABASE=${PGDATABASE}
            - PGUSER=${PGUSER}
            - PGPASSWORD=${PGPASSWORD}
        command: mlflow server --backend-store-uri postgresql://${PGUSER}:${PGPASSWORD}@postgres/${PGDATABASE}  --default-artifact-root s3://mlflow/ --host 0.0.0.0 -p 8000
